[package]
name = "rusty-core"
version = "0.1.0"
authors = ["Damian Reeves <957246+DamianReeves@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]
[dependencies]
